// <auto-generated />
namespace TrocadeIdeias.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ajusteemail_timespan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ajusteemail_timespan));
        
        string IMigrationMetadata.Id
        {
            get { return "201708250316017_ajusteemail_timespan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
